# The items in this configuration file correspond to the steps in the overall recipe.
# The values refer to configuration files of the individual steps.

defaults:
    - .@paths: paths
    - .@prepare_data: prepare_data
    - .@finetune_asr: finetune_asr
    - .@inference: inference
    - .@evaluate: evaluate
    - .@prepare_perturbed_data: prepare_perturbed_data
    - .@test_timestamps: test_timestamps
    - _self_

# Setting up paths for outputs of the experiments
exp_name: base
base_dir: exp/${exp_name}
hydra:
    run:
        dir:
            ${base_dir}/hydra


# If you wish to skip a step, set its value to null or false as below.
# This can be also done from command-line when running the script, e.g.
# python run.py prepare_data.run=false
prepare_data:
    run: true
finetune_asr:
    run: true
inference:
    run: true
evaluate:
    run: true
